### ISSUE TITLE
trainSegmentation.csv文件的格式

### ISSUE THREAD

**Issue by ylink-lfs** [junqiangchen/AttentionGatedVNet3D#1]
作者您好！我查找到您托管在github上的这个项目，对您的代码有兴趣尝试复现。您能否提供一下，在vnet3d_train.py文件中引用的trainSegmentation.csv这个文件，是按照什么规则储存图像的信息呢？感谢您的帮助！

**Comment by junqiangchen** [comment]
你好，
该文件格式可以参考一下KiTS19这个项目，在dataprocess这个文件目录下可以看到该文件是如何生成的。
